/**
 * Test fixture: the v1 master profile (legacy/v1/src/data/master-profile.json)
 * as a typed `UserProfile`. Generated by copying the JSON; `email_personal`
 * maps to `personal.email`, `email_work` and `copilot_365_detail` are not
 * part of the v2 type and are dropped. `id` is the literal 'fixture'.
 *
 * Used by the analyser tests so evidence strings can be checked against the
 * literal text of the profile. Not shipped to apps/web.
 */
import type { UserProfile } from '../types';

export const FIXTURE_PROFILE: UserProfile = {
  id: 'fixture',
  personal: {
    name: 'Matt Harkness',
    email: 'smharkness.nz@gmail.com',
    phone: '021 241 7033',
    address: '14 Madison Terrace, Silverdale, Auckland',
    linkedin: '',
    nationality: 'New Zealand',
    years_experience: 28,
  },
  executive_summary: 'AI and digital transformation leader with a track record of moving organisations from AI curiosity to AI reality by combining governance-first enablement, practical delivery, and operational cost discipline. Led production rollout of enterprise AI assistants, implemented AI-ready knowledge operating models, and established scalable governance for agent platforms at organisational scale. Strong security and risk background (Zero Trust, privileged access, device trust), with proven ability to align stakeholders, build business cases, and deliver durable operating models that teams can run.',
  core_competencies: [
    'Technology Roadmaps & Domain Strategy',
    'AI Product Delivery & Copilot Studio',
    'Enterprise Agent Governance & Cost Control',
    'Responsible AI & Operational Readiness',
    'Knowledge Operations & Automation',
    'Privileged Access Management (PAM)',
    'Zero Trust Device Model & Access Strategy',
    'Microsoft 365 | Intune | Windows 365 | Azure',
    'Endpoint Security & Cyber Risk Governance',
    'Agile Product & Platform Ownership',
    'Cross-functional Leadership & DevOps Transformation',
    'Financial Management (OPEX/CAPEX) & Forecasting',
    'Open Banking | API Platform Delivery',
    'AI/Data Governance & Responsible AI Practices',
    'Lean Six Sigma (Green Belt) | ITIL | CoBIT',
    'Stakeholder Engagement & Business Case Development',
    'Security Architecture (NIST CSF / ISO / NZISM)',
  ],
  career_history: [
    {
      title: 'Product Manager – Modern Workplace',
      company: 'One NZ (formerly Vodafone NZ)',
      location: 'Auckland, New Zealand',
      start_date: 'Nov 2021',
      end_date: 'Present',
      highlights: [
        'Led design and production rollout of a Teams-based AI support assistant built on Copilot Studio, anchored to curated internal knowledge sources with guardrails, establishing a scalable AI front door to trusted knowledge.',
        'Implemented automated knowledge lifecycle (ownership, review cadences, reminders, archiving) and integrated escalation handling to reduce knowledge debt and hallucination risk.',
        'Embedded Responsible AI controls and traceability into the operating model with governance-first, production service mindset.',
        'Introduced controls to prevent runaway agent costs; shifted to managed pay-as-you-go with explicit governance decisions.',
        'Built agentic automation business case covering ServiceNow, SharePoint, licensing, and Security Copilot-driven endpoint insights — forecast ~23% reduction in manual work.',
        'Produced vendor-agnostic Privileged Access Management reference architecture aligned to NIST CSF / ISO / NZISM.',
        'Authored device management standards defining tiered access pathways (secure browser, MAM, MDM, PAW) for Zero Trust.',
        'Developed licensing strategy guidelines for E5/F3/P2 allocation improving cost governance.',
        'Standardised DevOps work-item structures and enabled GitHub Copilot adoption across engineering teams.',
        'Own and govern Microsoft 365, Intune, and Windows 365 strategy across 6 FTEs and 4,000+ endpoints.',
        'Delivered zero-downtime organisational divestment and rebrand initiatives.',
        'Drove OPEX reduction through licensing optimisation and automation at scale.',
        'Lead technologist for Copilot 365 onboarding and adoption; active in the Microsoft community, drove product fixes.',
        'Used data analytics with Intune APIs and custom WMI calls to identify fleet-wide device performance issues, resulting in Lenovo revising Australasian marketing standards.',
      ],
      keywords: [
        'AI',
        'Copilot Studio',
        'Responsible AI',
        'PAM',
        'Zero Trust',
        'NIST',
        'Intune',
        'M365',
        'Windows 365',
        'DevOps',
        'Power Platform',
        'Agentic Automation',
        'Knowledge Management',
      ],
    },
    {
      title: 'Customer eXperience Owner (CXO) – Cloud Enablement',
      company: 'ASB Bank',
      location: 'Auckland, New Zealand',
      start_date: '2020',
      end_date: '2021',
      highlights: [
        'Led migration from VMware Horizon to Windows 365 Cloud PCs, achieving significant OPEX savings.',
        'Represented ASB in Payments NZ Open Banking working groups, influencing national API and security standards.',
        'Built cloud-native developer experience for internal APIs and SDKs across 4 squads.',
        'Governed Surface and Mac fleets (Intune + JAMF) and internal developer cloud SDKs.',
        'Directed the 180-day Windows 365 proof of concept (twice the normal Microsoft allowance), demonstrating feasibility and cost benefits.',
      ],
      keywords: [
        'Windows 365',
        'Cloud PC',
        'Open Banking',
        'JAMF',
        'Intune',
        'API',
        'CX',
        'OPEX reduction',
      ],
    },
    {
      title: 'Product Owner – Integration',
      company: 'ASB Bank',
      location: 'Auckland, New Zealand',
      start_date: '2018',
      end_date: '2020',
      highlights: [
        'Delivered $12M OPEX reduction by streamlining API platform operations and decommissioning legacy components.',
        'Led Open Banking initiatives, API SDLC automation, and full platform lifecycle governance.',
        'Successfully transformed Kiwisaver Fund processing, improving transaction uptime and reducing processing time.',
        'Integrated automation-first mindset across BizTalk, Layer 7, and APIGEE platforms.',
        'Implemented test-driven development with full traceability from business requirements to code-level test cases.',
      ],
      keywords: [
        'API',
        'Open Banking',
        'Integration',
        'BizTalk',
        'APIGEE',
        'Layer 7',
        'TDD',
        'OPEX reduction',
        'Kiwisaver',
      ],
    },
    {
      title: 'Software Integration Capability Lead',
      company: 'ASB Bank',
      location: 'Auckland, New Zealand',
      start_date: '2017',
      end_date: '2018',
      highlights: [
        'Led integration domain strategy including REST APIs, Kafka, WCF, and Layer 7.',
        'Transitioned teams to autonomous DevOps operating models with embedded platform monitoring.',
        'Delivered team uplift via coaching, availability management, and CI pipeline automation.',
      ],
      keywords: [
        'REST API',
        'Kafka',
        'DevOps',
        'CI/CD',
        'Integration',
        'Platform monitoring',
      ],
    },
    {
      title: 'Manager Database Operations',
      company: 'ASB Bank',
      location: 'Auckland, New Zealand',
      start_date: '2011',
      end_date: '2017',
      highlights: [
        'Managed 14,000+ databases across SQL Server, Oracle, MongoDB, and legacy platforms ensuring 24x7 availability.',
        'Delivered CoBIT integration, WorkSmart lean improvements, and DBA automation for compliance and efficiency.',
        'Led outsourcing strategies for Sybase and Informix, reducing cost and mitigating key-person risk.',
        'Oversaw regulatory database support for AML/Fraud and data protection projects.',
        'Drove a six-month cross-functional secondment program, rotating Delivery and Operations staff to uplift capability, deepen engagement, and retain critical talent.',
      ],
      keywords: [
        'SQL Server',
        'Oracle',
        'MongoDB',
        'CoBIT',
        'Lean',
        'Database',
        'AML',
        'Outsourcing',
        'People leadership',
      ],
    },
    {
      title: 'Earlier Career',
      company: 'Various (NZ-based)',
      location: 'New Zealand',
      start_date: '1998',
      end_date: '2011',
      highlights: [
        'Progressive career growth through database administration, systems administration, and infrastructure operations roles.',
        'Teradata systems administration and Unix shell scripting expertise.',
        'MCSE NT4 certified; foundation in Microsoft enterprise technologies.',
      ],
      keywords: [
        'DBA',
        'Systems Admin',
        'Infrastructure',
        'Teradata',
        'Unix',
        'MCSE',
      ],
    },
  ],
  certifications_and_training: [
    {
      name: 'Foundations of Responsible AI',
      year: 2024,
    },
    {
      name: 'Safeguarding AI',
      year: 2024,
    },
    {
      name: 'Ethics in the Age of Generative AI',
      year: 2024,
    },
    {
      name: 'Responsible AI: Principles and Practical Applications',
      year: 2024,
    },
    {
      name: 'Introduction to Responsible AI Algorithm Design',
      year: 2024,
    },
    {
      name: 'Microsoft 365: Manage Governance and Compliance',
      year: 2023,
    },
    {
      name: 'Microsoft Azure AI Fundamentals',
      year: 2023,
    },
    {
      name: 'Microsoft Azure Power Platform Fundamentals',
      year: 2023,
    },
    {
      name: 'Microsoft Azure Fundamentals',
      year: 2023,
    },
    {
      name: 'Get Ready for Generative AI',
      year: 2023,
    },
    {
      name: 'Human Centred Design Essentials',
      year: 2022,
    },
    {
      name: 'Cybersecurity at Work',
      year: 2022,
    },
    {
      name: 'Agile for Distributed Teams',
      year: 2022,
    },
    {
      name: 'Cloud Architecture: Core Concepts',
      year: 2021,
    },
    {
      name: 'Windows 10: Intune Device Management',
      year: 2021,
    },
    {
      name: 'Cloud Management with Microsoft Endpoint Manager',
      year: 2021,
    },
    {
      name: 'Critical Thinking',
      year: 2021,
    },
    {
      name: 'WorkSmart Greenbelt (Lean Six Sigma)',
      year: 2021,
    },
    {
      name: 'WorkSmart Fundamentals (Lean Six Sigma)',
      year: 2020,
    },
    {
      name: 'WorkSmart Essentials (Lean Six Sigma)',
      year: 2019,
    },
    {
      name: 'Strategic Agility',
      year: 2018,
    },
    {
      name: 'Agile Essentials',
      year: 2018,
    },
    {
      name: 'ITIL2 Service Management Essentials',
      year: 2017,
    },
    {
      name: 'ITIL Service Management Essentials',
      year: 2011,
    },
    {
      name: 'Kepner-Tregoe Project Management',
      year: 2001,
    },
    {
      name: 'MCSE NT4, MCP+I, MCP (ID 1715984)',
      year: 1998,
    },
  ],
};
