import Database from "better-sqlite3";
import archiver from "archiver";
import { Writable } from "stream";
import type { Flashcard } from "./flashcard-generator";

/**
 * Generate an .apkg (Anki Package) file from flashcards.
 *
 * An .apkg file is a ZIP archive containing:
 * - collection.anki2 (SQLite database with Anki schema)
 * - media (empty JSON object for no media)
 */

const MODEL_ID = 1700000000000;
const DECK_ID = 1700000000001;

export async function exportToAPKG(
  cards: Flashcard[],
  deckName: string
): Promise<Buffer> {
  // 1. Create SQLite database in memory
  const db = new Database(":memory:");

  // Create Anki schema
  db.exec(`
    CREATE TABLE col (
      id integer PRIMARY KEY,
      crt integer NOT NULL,
      mod integer NOT NULL,
      scm integer NOT NULL,
      ver integer NOT NULL,
      dty integer NOT NULL,
      usn integer NOT NULL,
      ls integer NOT NULL,
      conf text NOT NULL,
      models text NOT NULL,
      decks text NOT NULL,
      dconf text NOT NULL,
      tags text NOT NULL
    );

    CREATE TABLE notes (
      id integer PRIMARY KEY,
      guid text NOT NULL,
      mid integer NOT NULL,
      mod integer NOT NULL,
      usn integer NOT NULL,
      tags text NOT NULL,
      flds text NOT NULL,
      sfld text NOT NULL,
      csum integer NOT NULL,
      flags integer NOT NULL,
      data text NOT NULL
    );

    CREATE TABLE cards (
      id integer PRIMARY KEY,
      nid integer NOT NULL,
      did integer NOT NULL,
      ord integer NOT NULL,
      mod integer NOT NULL,
      usn integer NOT NULL,
      type integer NOT NULL,
      queue integer NOT NULL,
      due integer NOT NULL,
      ivl integer NOT NULL,
      factor integer NOT NULL,
      reps integer NOT NULL,
      lapses integer NOT NULL,
      left integer NOT NULL,
      odue integer NOT NULL,
      odid integer NOT NULL,
      flags integer NOT NULL,
      data text NOT NULL
    );

    CREATE TABLE revlog (
      id integer PRIMARY KEY,
      cid integer NOT NULL,
      usn integer NOT NULL,
      ease integer NOT NULL,
      ivl integer NOT NULL,
      lastIvl integer NOT NULL,
      factor integer NOT NULL,
      time integer NOT NULL,
      type integer NOT NULL
    );

    CREATE TABLE graves (
      usn integer NOT NULL,
      oid integer NOT NULL,
      type integer NOT NULL
    );
  `);

  const now = Math.floor(Date.now() / 1000);

  // Model (note type) definition — Basic with Front/Back
  const models = JSON.stringify({
    [MODEL_ID]: {
      id: MODEL_ID,
      name: "ApplyForMe Basic",
      type: 0,
      mod: now,
      usn: -1,
      sortf: 0,
      did: DECK_ID,
      tmpls: [
        {
          name: "Card 1",
          ord: 0,
          qfmt: "{{Front}}",
          afmt: "{{FrontSide}}<hr id='answer'>{{Back}}",
          bqfmt: "",
          bafmt: "",
        },
      ],
      flds: [
        { name: "Front", ord: 0, sticky: false, rtl: false, font: "Arial", size: 20, media: [] },
        { name: "Back", ord: 1, sticky: false, rtl: false, font: "Arial", size: 20, media: [] },
      ],
      css: ".card { font-family: arial; font-size: 16px; text-align: left; color: #333; background-color: white; padding: 20px; } b { color: #1a365d; }",
      latexPre: "",
      latexPost: "",
      latexsvg: false,
      req: [[0, "all", [0]]],
      tags: [],
      vers: [],
    },
  });

  // Deck definition
  const decks = JSON.stringify({
    1: { id: 1, name: "Default", mod: now, usn: -1, lrnToday: [0, 0], revToday: [0, 0], newToday: [0, 0], timeToday: [0, 0], collapsed: false, desc: "" },
    [DECK_ID]: { id: DECK_ID, name: deckName, mod: now, usn: -1, lrnToday: [0, 0], revToday: [0, 0], newToday: [0, 0], timeToday: [0, 0], collapsed: false, desc: `Generated by ApplyForMe on ${new Date().toLocaleDateString("en-NZ")}` },
  });

  const dconf = JSON.stringify({
    1: { id: 1, name: "Default", replayq: true, lapse: { delays: [10], mult: 0, minInt: 1, leechFails: 8, leechAction: 0 }, rev: { perDay: 200, ease4: 1.3, fuzz: 0.05, minSpace: 1, ivlFct: 1, maxIvl: 36500, buried: false }, new: { delays: [1, 10], ints: [1, 4, 7], initialFactor: 2500, separate: true, order: 1, perDay: 20, buried: false }, maxTaken: 60, timer: 0, autoplay: true, mod: 0, usn: 0 },
  });

  const conf = JSON.stringify({
    nextPos: 1,
    estTimes: true,
    activeDecks: [1],
    sortType: "noteFld",
    timeLim: 0,
    sortBackwards: false,
    addToCur: true,
    curDeck: 1,
    newSpread: 0,
    dueCounts: true,
    curModel: MODEL_ID,
    collapseTime: 1200,
  });

  // Insert collection metadata
  db.prepare(`
    INSERT INTO col VALUES (1, ?, ?, ?, 11, 0, 0, 0, ?, ?, ?, ?, '{}')
  `).run(now, now, now, conf, models, decks, dconf);

  // Insert cards
  const insertNote = db.prepare(`
    INSERT INTO notes VALUES (?, ?, ?, ?, -1, ?, ?, ?, ?, 0, '')
  `);
  const insertCard = db.prepare(`
    INSERT INTO cards VALUES (?, ?, ?, 0, ?, -1, 0, 0, ?, 0, 0, 0, 0, 0, 0, 0, 0, '')
  `);

  for (let i = 0; i < cards.length; i++) {
    const card = cards[i];
    const noteId = MODEL_ID + i + 1;
    const cardId = MODEL_ID + cards.length + i + 1;
    const guid = generateGuid();
    const tags = card.tags.join(" ");
    const flds = `${card.front}\x1f${card.back}`;
    const sfld = card.front;
    const csum = fieldChecksum(sfld);

    insertNote.run(noteId, guid, MODEL_ID, now, tags, flds, sfld, csum);
    insertCard.run(cardId, noteId, DECK_ID, now, i);
  }

  // Export SQLite to buffer
  const sqliteBuffer = db.serialize();
  db.close();

  // 2. Create ZIP archive with .anki2 file and empty media
  return new Promise<Buffer>((resolve, reject) => {
    const chunks: Buffer[] = [];
    const writable = new Writable({
      write(chunk, _encoding, callback) {
        chunks.push(Buffer.from(chunk));
        callback();
      },
    });

    const archive = archiver("zip", { zlib: { level: 6 } });
    archive.pipe(writable);

    archive.append(Buffer.from(sqliteBuffer), { name: "collection.anki2" });
    archive.append("{}", { name: "media" });

    writable.on("finish", () => {
      resolve(Buffer.concat(chunks));
    });

    archive.on("error", reject);
    archive.finalize();
  });
}

function generateGuid(): string {
  const chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
  let result = "";
  for (let i = 0; i < 10; i++) {
    result += chars[Math.floor(Math.random() * chars.length)];
  }
  return result;
}

function fieldChecksum(field: string): number {
  // Simple checksum matching Anki's algorithm (first 8 hex digits of SHA1)
  let hash = 0;
  for (let i = 0; i < field.length; i++) {
    const char = field.charCodeAt(i);
    hash = ((hash << 5) - hash + char) | 0;
  }
  return Math.abs(hash);
}
